// <auto-generated />
using System;
using ArquiteturaCamadasREST.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArquiteturaCamadasREST.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230809001441_MigrateInicial")]
    partial class MigrateInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Emprestado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataEmprestado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_emprestado");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint")
                        .HasColumnName("livro_id");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("PessoaId");

                    b.ToTable("emprestado");
                });

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("autor");

                    b.Property<int>("Edicao")
                        .HasColumnType("int")
                        .HasColumnName("edicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("livro");
                });

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("genero");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sobrenome");

                    b.HasKey("Id");

                    b.ToTable("pessoa");
                });

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Emprestado", b =>
                {
                    b.HasOne("ArquiteturaCamadasREST.Models.Livro", "Livro")
                        .WithMany("Emprestado")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArquiteturaCamadasREST.Models.Pessoa", "Pessoa")
                        .WithMany("Emprestado")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Livro", b =>
                {
                    b.Navigation("Emprestado");
                });

            modelBuilder.Entity("ArquiteturaCamadasREST.Models.Pessoa", b =>
                {
                    b.Navigation("Emprestado");
                });
#pragma warning restore 612, 618
        }
    }
}
